---
# ====== Application: Team Calendar ==========================
id: 118
identification: 
  name: Team Calendar
  alias: TEAM-CALENDAR
  version: 24.2.1
  application-group: Starter Apps # 189034225876496944

row-search: 
  tokenize: false
  text-query-function: None

availability: 
  status: Available with Developer Toolbar
  build-status: Run and Build Application

error-handling: 
  default-display-location: Inline with Field and in Notification
  error-handling-function: eba_ca_fw.apex_error_handling

report-printing: 
  type: Use Instance Settings

advanced: 
  friendly-urls: true
  allow-feedback: false
  logging: true
  debugging: false
  compatibility-mode: 24.2
  accessible-read-only-items: true
  pass-ecid: N
  copyright-banner: |
    Name: #APP_NAME#
    Copyright (c)2012, #YEAR# Oracle and/or its affiliates.
    Licensed under the Universal Permissive License v 1.0 as shown 
    at https://oss.oracle.com/licenses/upl/
    
    This script makes use of the FullCalendar product. Refer to
    THIRD_PARTY_LICENSES.txt in the top directory of this project
    or at https://github.com/oracle/apex for license information.

authentication: 
  public-user: APEX_PUBLIC_USER
  authentication-scheme: APEX Accounts # 8949801941501567742

authorization: 
  authorization-scheme: APPLICATION SENTRY # 3264368374772348877
  run-on-public-pages: false
  run-on-background-job: true
  source-for-role-or-group-schemes: Access Control User Role Assignments

session-management: 
  rejoin-sessions: Enabled for Public Sessions
  maximum-session-length: 28800
  maximum-session-idle-time: 28800

session-state-protection: 
  enabled: true

security: 
  deep-linking: Enabled
  browser-cache: Disabled
  embed-in-frames: Allow from same origin
  referrer-policy: strict-origin
  html-escaping-mode: Extended
  runtime-api-usage: 
  - Modify This Application

database-session: 
  parsing-schema: JESS_DEV_2

globalization: 
  primary-language: English (en)
  document-direction: Left-To-Right
  language-derived-from: Application Primary Language
  automatic-time-zone: false
  automatic-csv-encoding: true

application-format-masks: 
  date: '&APP_DATE_FORMAT.'
  timestamp: '&APP_TIMESTAMP_FORMAT.'

character-value-comparison: 
  behavior: Database session NLS setting (default)

logo: 
  type: Text
  text: '&APPLICATION_TITLE.'

progressive-web-app: 
  enable: false

navigation: 
  home-url: 
    url: 'f?p=&APP_ID.:1:&SESSION.'
    page: 1 # Home

navigation-menu: 
  list-template: Side Navigation Menu
  template-options: 
  - '#DEFAULT#'
  - js-defaultCollapsed
  - js-navCollapsed--hidden
  - t-TreeNav--styleA
  list-position: Side
  list: Navigation Menu # 1760666398868434401

navigation-bar: 
  implementation: List
  list: Navigation Bar # 1226288688404772270
  list-template: Navigation Bar

javascript: 
  include-deprecated-or-desupported-javascript-functions: 
  - Pre 18.1
  - 18.x
  include-jquery-migrate: false

css: 
  file-urls: 
  - '#IMAGE_PREFIX#pkgapp_ui/css/5.0#MIN#.css'

attributes: 
  theme: Universal Theme # 42
  global-page: 0
  enable-end-users-to-choose-theme-style: true
  add-"built-with-apex"-to-footer: true
  auto-dismiss-success-messages: false

subscription: 
  version-number: 82521914

substitutions: 
- # ====== Substitution: APP_DATE_FORMAT =======================
  id: 1
  identification: 
    name: APP_DATE_FORMAT

  value: 
    static-value: DD-Mon-RRRR

- # ====== Substitution: APP_TIME_FORMAT =======================
  id: 2
  identification: 
    name: APP_TIME_FORMAT

  value: 
    static-value: 'HH:MIam'

- # ====== Substitution: APP_TIMESTAMP_FORMAT ==================
  id: 3
  identification: 
    name: APP_TIMESTAMP_FORMAT

  value: 
    static-value: 'DSFM HH24:MI:SS'

- # ====== Substitution: APP_DATETIME_FORMAT ===================
  id: 4
  identification: 
    name: APP_DATETIME_FORMAT

  value: 
    static-value: 'DD-Mon-RRRR HH:MIam'

- # ====== Substitution: APP_NAME ==============================
  id: 5
  identification: 
    name: APP_NAME

  value: 
    static-value: Team Calendar

component-settings: 
- # ====== Component Setting: NATIVE_BOSS ======================
  id: 29431774233173013
  identification: 
    name: NATIVE_BOSS
    type: REST Data Source

  subscription: 
    version-number: 187973429

- # ====== Component Setting: NATIVE_STAR_RATING ===============
  id: 30734327339667925
  identification: 
    name: NATIVE_STAR_RATING
    type: Item

  subscription: 
    version-number: 37166093807269

- # ====== Component Setting: NATIVE_OPEN_AI_ASSISTANT =========
  id: 30923382297643886
  identification: 
    name: NATIVE_OPEN_AI_ASSISTANT
    type: Dynamic Action

  subscription: 
    version-number: 37167665066283

- # ====== Component Setting: NATIVE_SELECT_MANY ===============
  id: 30923734477643886
  identification: 
    name: NATIVE_SELECT_MANY
    type: Item

  subscription: 
    version-number: 37167665066283

- # ====== Component Setting: NATIVE_GEOCODING =================
  id: 30947347166492425
  identification: 
    name: NATIVE_GEOCODING
    type: Process

  settings: 
    attribute-1: RELAX_HOUSE_NUMBER

  subscription: 
    version-number: 155456021

- # ====== Component Setting: NATIVE_GEOCODED_ADDRESS ==========
  id: 129276862867061913
  identification: 
    name: NATIVE_GEOCODED_ADDRESS
    type: Item

  subscription: 
    version-number: 37166093807272

- # ====== Component Setting: NATIVE_MAP_REGION ================
  id: 150306763778350491
  identification: 
    name: NATIVE_MAP_REGION
    type: Region

  subscription: 
    version-number: 37166093807272

- # ====== Component Setting: NATIVE_DATE_PICKER_APEX ==========
  id: 152646050736651475
  identification: 
    name: NATIVE_DATE_PICKER_APEX
    type: Item

  subscription: 
    version-number: 37166093807273

- # ====== Component Setting: NATIVE_SINGLE_CHECKBOX ===========
  id: 205561006805679828
  identification: 
    name: NATIVE_SINGLE_CHECKBOX
    type: Item

  subscription: 
    version-number: 37166093807275

- # ====== Component Setting: NATIVE_ADFBC =====================
  id: 636139807537779412
  identification: 
    name: NATIVE_ADFBC
    type: REST Data Source

  subscription: 
    version-number: 37166093806701

- # ====== Component Setting: NATIVE_YES_NO ====================
  id: 1149916498435648019
  identification: 
    name: NATIVE_YES_NO
    type: Item

  subscription: 
    version-number: 37166093807277

- # ====== Component Setting: NATIVE_DISPLAY_SELECTOR ==========
  id: 1797022758498564414
  identification: 
    name: NATIVE_DISPLAY_SELECTOR
    type: Region

  subscription: 
    version-number: 37166093807277

- # ====== Component Setting: NATIVE_IR ========================
  id: 1863723394177846509
  identification: 
    name: NATIVE_IR
    type: Region

  subscription: 
    version-number: 37166093807280

- # ====== Component Setting: NATIVE_COLOR_PICKER ==============
  id: 1949634515608792536
  identification: 
    name: NATIVE_COLOR_PICKER
    type: Item

  subscription: 
    version-number: 37166093807281

